"""Database package for Grouper."""

from .activities import (
    BACKGROUND_GROUP_NAME,
    add_activity_group,
    archive_activity,
    create_activity,
    create_group,
    delete_activity,
    delete_group,
    ensure_background_group,
    get_activities_by_group,
    get_activity,
    get_activity_by_id,
    get_activity_groups,
    get_all_groups,
    get_group_by_id,
    get_group_by_name,
    get_or_create_activity,
    get_or_create_group,
    get_ungrouped_activities,
    list_activities,
    list_all_groups,
    remove_activity_group,
    rename_activity_by_id,
    rename_group,
    set_activity_groups,
    soft_delete_activity,
    unarchive_activity,
    update_activity,
)
from .boards import (
    create_board,
    delete_board,
    get_board,
    get_board_by_id,
    get_or_create_default_board,
    list_boards,
    rename_board,
)
from .calendars import (
    archive_calendar,
    create_calendar,
    get_calendar,
    get_default_calendar_id,
    list_calendars,
    set_default_calendar,
    update_calendar,
)
from .connection import (
    backup_database,
    get_connection,
    init_database,
    register_data_changed_callback,
    unregister_data_changed_callback,
)
from .events import (
    create_event,
    delete_event,
    get_event,
    list_events_for_range,
    update_event,
)
from .prerequisites import (
    add_prerequisite,
    cleanup_prerequisites_for_deleted_task,
    get_prerequisite_ids,
    get_prerequisite_tasks,
    get_prerequisite_tasks_for_ids,
    get_unmet_prerequisites,
    remove_prerequisite,
)
from .projects import (
    archive_project,
    create_project,
    delete_project,
    get_or_create_project,
    get_project,
    get_starred_projects,
    list_projects,
    rename_project,
    unarchive_project,
    update_project,
)
from .sessions import (
    delete_session,
    export_sessions_csv,
    get_active_session,
    get_active_session_by_activity,
    get_active_sessions,
    get_session_by_id,
    get_sessions,
    get_summary,
    get_summary_by_day,
    log_session,
    pause_session,
    resume_session,
    split_sessions_at_midnight,
    start_session,
    stop_all_sessions,
    stop_session,
)
from .settings import get_setting, set_setting
from .tags import (
    add_tag_to_activity,
    add_tag_to_project,
    add_tag_to_task,
    create_tag,
    get_activity_tags,
    get_or_create_tag,
    get_project_tags,
    get_tag,
    get_tags_for_activity_ids,
    get_tags_for_project_ids,
    get_tags_for_task_ids,
    get_task_tags,
    list_tags,
    remove_tag_from_activity,
    remove_tag_from_project,
    remove_tag_from_task,
)
from .task_links import (
    add_link,
    delete_link,
    get_links_for_task,
    get_links_for_task_ids,
    update_link,
)
from .tasks import (
    complete_task,
    create_task,
    create_task_with_relations,
    delete_task,
    get_completed_tasks,
    get_starred_tasks,
    get_task,
    get_tasks,
    get_tasks_by_board,
    get_tasks_with_due_dates,
    get_unscheduled_starred_tasks,
    get_unscheduled_tasks_for_starred_projects,
    uncomplete_task,
    update_task,
)
